version: '3'
services:
  redis:
    image: redis:latest
    container_name: rate-limiter-redis
    ports:
      - "6379:6379"
    networks:
      - rate-limiter

networks:
  rate-limiter:
    name: rate-limiter
    driver: bridge
